### ISSUE TITLE
I need to install this on a server that does not have an internet connection.  Is there a vsix file?

### ISSUE THREAD

**Issue by blacksburgturkey** [Microsoft/vscode-anaconda-extension-pack#5]
I need to install this on a server that does not have an internet connection.  Is there a vsix file?

**Comment by brettcannon** [comment]
If you look at [the extension's page on the Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.anaconda-extension-pack) you will find a "Download Extension" link. But do realize that since this extension is an extension pack, all that's going to do is cause VS Code to try and download the individual extensions. 😁 

What you actually want to do is download the individual extensions that the extension pack references (which are listed in the README).
